package com.primus.admin.zone.service;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.AbstractService;
import com.primus.admin.zone.model.Zone;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import com.primus.abstracts.PrimusModel;
import com.primus.admin.zone.dao.ZoneDAO;



/**
** Class Generated by Primus Auto code generator
**/
@Component
@Transactional
public class ZoneService extends AbstractService {


 @Autowired
 ZoneDAO zoneDAO ;

  @Override
     public AbstractDAO getDAO() {
         return zoneDAO;
     }


      @Override
     protected void collateBeforUpdate(PrimusModel newObject, PrimusModel oldObject) {
         Zone newObj = (Zone) newObject;
         Zone oldObj = (Zone) oldObject;
         /*TransactionUpdateDelta delta = formDelta(oldObj.getPayScaleSplits(), ((PayScale) newObj).getPayScaleSplits()) ;
         payScale.getPayScaleSplits().addAll((List<PayScaleSplit>)delta.getDeletedRecords());*/
     }

}