package com.primus.crm.appointment.controller;

import com.primus.abstracts.AbstractCRUDController;;
import java.util.LinkedHashMap;
import java.util.Map;


/**
** Class Generated by Primus Auto code generator
**/
public class AppointmentTemplateController extends AbstractCRUDController{

    @Override
    protected String getServiceName() {
        return "AppointmentTemplateService";
    }


    @Override
    protected String getValidatorName() {
        return "AppointmentTemplateValidator";
    }

     

}