package com.primus.crm.appointment.controller;

import com.primus.abstracts.AbstractCRUDController;
import com.techtrade.rads.framework.model.abstracts.ModelObject;
import com.techtrade.rads.framework.ui.abstracts.PageResult;;
import java.util.LinkedHashMap;
import java.util.Map;


/**
** Class Generated by Primus Auto code generator
**/
public class AppointmentController extends AbstractCRUDController{

    @Override
    protected String getServiceName() {
        return "AppointmentService";
    }


    @Override
    protected String getValidatorName() {
        return "AppointmentValidator";
    }

    private String prefixZero( int value )
    {
        return (value<10)?"0"+value:String.valueOf(value);
    }
    public Map<String, String> getHours() {
        Map<String, String> ans = new LinkedHashMap<String, String>() ;
        for (int i =0 ;  i< 24 ; i ++) {
            ans.put(String.valueOf(i),prefixZero(i));
        }
        return ans;
    }



    public Map<String, String> getMinutes() {
        Map<String, String> ans = new LinkedHashMap<String, String>() ;
        ans.put("00","00");
        ans.put("15","15");
        ans.put("30","30");
        ans.put("45","45");
        return ans;

    }

    @Override
    public PageResult submit(ModelObject object, String actionParam) {
        if ("CANCEL_APPOINTMENT".equalsIgnoreCase(actionParam)) {

        }
        return super.submit(object, actionParam);
    }
}