package com.primus.crm.appointment.controller;

import com.primus.abstracts.AbstractListController;
import com.primus.common.CommonUtil;
import com.primus.common.FVConstants;


import java.util.Map;

/**
** Class Generated by Primus Auto code generator
**/
public class AppointmentTemplateListController extends AbstractListController{

     @Override
       protected String getServiceName() {
           return "AppointmentTemplateService";
       }


    @Override
    protected String getAddEditPageKey() {
        return "newappointmenttemplate";
    }

    @Override
    protected String getValidatorName() {
        return "AppointmentTemplateValidator";
    }

}