package com.primus.merchandise.item.controller;

import com.primus.abstracts.AbstractTransactionController;;
import java.util.LinkedHashMap;
import java.util.Map;


/**
 * * Class Generated by Primus Auto code generator
 **/
public class ItemController extends AbstractTransactionController {

    @Override
    protected String getServiceName() {
        return "ItemService";
    }


    @Override
    protected String getValidatorName() {
        return "ItemValidator";
    }


    public Map<String, String> getProducts() {
        Map<String, String> ans = new LinkedHashMap<>();

        return ans;
    }

    public Map<String, String> getMeasureUOMs() {
        Map<String, String> ans = new LinkedHashMap<>();

        return ans;
    }

    public Map<String, String> getSaleUOMs() {
        Map<String, String> ans = new LinkedHashMap<>();

        return ans;
    }


}