package com.primus.merchandise.item.controller;

import com.primus.abstracts.AbstractListController;
import com.primus.common.CommonUtil;
import com.primus.common.FVConstants;


import java.util.Map;

/**
** Class Generated by Primus Auto code generator
**/
public class ItemListController extends AbstractListController{

     @Override
       protected String getServiceName() {
           return "ItemService";
       }


    @Override
    protected String getAddEditPageKey() {
        return "newitem";
    }

    @Override
    protected String getValidatorName() {
        return "ItemValidator";
    }

}