package com.primus.merchandise.sku.controller;

import com.primus.abstracts.AbstractTransactionController;;
import java.util.LinkedHashMap;
import java.util.Map;


/**
** Class Generated by Primus Auto code generator
**/
public class SkuController extends AbstractTransactionController{

    @Override
    protected String getServiceName() {
        return "SkuService";
    }


    @Override
    protected String getValidatorName() {
        return "SkuValidator";
    }

     
 public Map<String, String > getSaleUOMs() 
 {
        Map<String , String > ans = new LinkedHashMap<>() ;

        return ans;
    }
 

}