package com.primus.merchandise.sku.controller;

import com.primus.abstracts.AbstractListController;
import com.primus.common.CommonUtil;
import com.primus.common.FVConstants;


import java.util.Map;

/**
** Class Generated by Primus Auto code generator
**/
public class SkuListController extends AbstractListController{

     @Override
       protected String getServiceName() {
           return "SkuService";
       }


    @Override
    protected String getAddEditPageKey() {
        return "newsku";
    }

    @Override
    protected String getValidatorName() {
        return "SkuValidator";
    }

}