package com.primus.admin.department.controller;

import com.primus.abstracts.AbstractCRUDController;

/**
** Class Generated by Primus Auto code generator
**/
public class DepartmentController extends AbstractCRUDController{

    @Override
    protected String getServiceName() {
        return "DepartmentService";
    }


    @Override
    protected String getValidatorName() {
        return "DepartmentValidator";
    }


}