package com.primus.admin.department.controller;

import com.primus.abstracts.AbstractListController;
import com.primus.common.CommonUtil;
import com.primus.common.FVConstants;


import java.util.Map;

/**
** Class Generated by Primus Auto code generator
**/
public class DepartmentListController extends AbstractListController{

     @Override
       protected String getServiceName() {
           return "DepartmentService";
       }


    @Override
    protected String getAddEditPageKey() {
        return "newdepartment";
    }

    @Override
    protected String getValidatorName() {
        return "DepartmentValidator";
    }

}