package com.primus.admin.division.dao;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.PrimusModel;
import com.primus.admin.division.service.DivisionService;
import com.techtrade.rads.framework.utils.Utils;
import org.springframework.stereotype.Component;
import com.primus.admin.division.model.Division;

import javax.persistence.Query;
import java.util.List;

/**
** Class Generated by Primus Auto code generator
**/
@Component
public class DivisionDAO extends AbstractDAO{

  @Override
    public String getEntityClassName() {
        return  "Division";
    }

    @Override
    public Class getEntityClass() {
        return  Division.class;
    }

    public Division getByName( String name , int company  ) {

        Query query =  em.createQuery("from  Division division where division.name = :name  and company.id = :company and deleted =false  " );
        query.setParameter("name", name);
        query.setParameter("company", company);
        List<Division> ans = query.getResultList();
        if (Utils.isNullList(ans))
            return null;
        else
            return ans.get(0);
    }
}

