package com.primus.admin.region.dao;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.PrimusModel;
import com.primus.admin.region.model.Location;
import org.springframework.stereotype.Component;
import com.primus.admin.region.model.Region;

/**
** Class Generated by Primus Auto code generator
**/
@Component
public class RegionDAO extends AbstractDAO{

  @Override
    public String getEntityClassName() {
        return  "Region";
    }

    @Override
    public Class getEntityClass() {
        return  Region.class;
    }

    public Location getLocationById(int id ) {
        return (Location) em.find(Location.class,id);
    }


}

