package com.primus.merchandise.category.service;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.AbstractService;
import com.primus.merchandise.category.model.Category;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import com.primus.abstracts.PrimusModel;
import com.primus.merchandise.category.dao.CategoryDAO;



/**
** Class Generated by Primus Auto code generator
**/
@Component
@Transactional
public class CategoryService extends AbstractService {


 @Autowired
 CategoryDAO categoryDAO ;

  @Override
     public AbstractDAO getDAO() {
         return categoryDAO;
     }


      @Override
     protected void collateBeforUpdate(PrimusModel newObject, PrimusModel oldObject) {
         Category newObj = (Category) newObject;
         Category oldObj = (Category) oldObject;
         /*TransactionUpdateDelta delta = formDelta(oldObj.getPayScaleSplits(), ((PayScale) newObj).getPayScaleSplits()) ;
         payScale.getPayScaleSplits().addAll((List<PayScaleSplit>)delta.getDeletedRecords());*/
     }

}