package com.primus.merchandise.category.validator;

import com.primus.abstracts.AbstractValidator;
import com.primus.abstracts.CommonErrorCodes;
import com.primus.abstracts.PrimusBusinessModel;
import com.primus.abstracts.PrimusModel;
import com.primus.common.ProductContext;
import com.techtrade.rads.framework.model.abstracts.RadsError;
import com.techtrade.rads.framework.utils.Utils;
import org.springframework.stereotype.Component;
import java.util.ArrayList;
import java.util.List;
import com.primus.merchandise.category.model.Category;


/**
** Class Generated by Primus Auto code generator
**/
@Component
public class CategoryValidator extends AbstractValidator {

@Override
    public String getBusinessKeyField() {
        return "Name";
    }

    @Override
    public List<RadsError> checkforMandatoryFields(PrimusModel model, ProductContext context) {
        Category category = (Category) model;
        List<RadsError> results =new ArrayList<RadsError>();
                if(Utils.isNull(category.getName  () ) ) {
            results.add( getErrorforCode(context, CommonErrorCodes.CANNOT_BE_EMPTY,"Name"));
        }

                if(Utils.isNull(category.getType  () ) ) {
            results.add( getErrorforCode(context, CommonErrorCodes.CANNOT_BE_EMPTY,"Type"));
        }

        
        return results;

     }

     @Override
    public List<RadsError> checkforValueRanges(PrimusModel model, ProductContext context) {
        return null;
    }

    @Override
    public List<RadsError> adaptFromUI(PrimusModel model, ProductContext context) {
       super.adaptFromUI(model,context) ;
       return null;
    }
}