package com.primus.admin.division.controller;

import com.primus.abstracts.AbstractListController;
import com.primus.common.CommonUtil;
import com.primus.common.FVConstants;


import java.util.Map;

/**
** Class Generated by Primus Auto code generator
**/
public class DivisionListController extends AbstractListController{

     @Override
       protected String getServiceName() {
           return "DivisionService";
       }


    @Override
    protected String getAddEditPageKey() {
        return "newdivision";
    }

    @Override
    protected String getValidatorName() {
        return "DivisionValidator";
    }
}