package com.primus.admin.division.controller;

import com.primus.abstracts.AbstractCRUDController;

/**
** Class Generated by Primus Auto code generator
**/
public class DivisionController extends AbstractCRUDController{

    @Override
    protected String getServiceName() {
        return "DivisionService";
    }


    @Override
    protected String getValidatorName() {
        return "DivisionValidator";
    }


}