package com.primus.merchandise.product.controller;

import com.primus.abstracts.AbstractDataSheetController;;
import java.util.LinkedHashMap;
import java.util.Map;


/**
** Class Generated by Primus Auto code generator
**/
public class ProductController extends AbstractDataSheetController{

    @Override
    protected String getServiceName() {
        return "ProductService";
    }


    @Override
    protected String getValidatorName() {
        return "ProductValidator";
    }

     
 public Map<String, String > getCategories() 
 {
        Map<String , String > ans = new LinkedHashMap<>() ;

        return ans;
    }
 

}