package com.primus.merchandise.product.controller;

import com.primus.abstracts.AbstractListController;
import com.primus.common.CommonUtil;
import com.primus.common.FVConstants;


import java.util.Map;

/**
** Class Generated by Primus Auto code generator
**/
public class ProductListController extends AbstractListController{

     @Override
       protected String getServiceName() {
           return "ProductService";
       }


    @Override
    protected String getAddEditPageKey() {
        return "newproduct";
    }

    @Override
    protected String getValidatorName() {
        return "ProductValidator";
    }

}