package com.primus.admin.reasoncode.validator;

import com.primus.abstracts.AbstractValidator;
import com.primus.abstracts.CommonErrorCodes;
import com.primus.abstracts.PrimusBusinessModel;
import com.primus.abstracts.PrimusModel;
import com.primus.common.ProductContext;
import com.techtrade.rads.framework.model.abstracts.RadsError;
import com.techtrade.rads.framework.utils.Utils;
import org.springframework.stereotype.Component;
import java.util.ArrayList;
import java.util.List;
import com.primus.admin.reasoncode.model.ReasonCode;


/**
** Class Generated by Primus Auto code generator
**/
@Component
public class ReasonCodeValidator extends AbstractValidator {

@Override
    public String getBusinessKeyField() {
        return "Reason";
    }

    @Override
    public List<RadsError> checkforMandatoryFields(PrimusModel model, ProductContext context) {
        ReasonCode reasonCode = (ReasonCode) model;
        List<RadsError> results =new ArrayList<RadsError>();
                if(Utils.isNull(reasonCode.getReason  () ) ) {
            results.add( getErrorforCode(context, CommonErrorCodes.CANNOT_BE_EMPTY,"Reason"));
        }

                if(Utils.isNull(reasonCode.getReasonType  () ) ) {
            results.add( getErrorforCode(context, CommonErrorCodes.CANNOT_BE_EMPTY,"Type"));
        }

                if(Utils.isNull(reasonCode.getFactorType  () ) ) {
            results.add( getErrorforCode(context, CommonErrorCodes.CANNOT_BE_EMPTY,"Factor"));
        }

                if(Utils.isNull(reasonCode.getOrientation  () ) ) {
            results.add( getErrorforCode(context, CommonErrorCodes.CANNOT_BE_EMPTY,"Orientation"));
        }

        
        return results;

     }

     @Override
    public List<RadsError> checkforValueRanges(PrimusModel model, ProductContext context) {
        return null;
    }

    @Override
    public List<RadsError> adaptFromUI(PrimusModel model, ProductContext context) {
       super.adaptFromUI(model,context) ;

       return null;
    }
}