package com.primus.admin.division.service;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.AbstractService;
import com.primus.common.ProductContext;
import com.primus.admin.division.model.Division;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import com.primus.admin.division.dao.DivisionDAO;



/**
** Class Generated by Primus Auto code generator
**/
@Component
@Transactional
public class DivisionService extends AbstractService {


 @Autowired
 DivisionDAO divisionDAO ;

  @Override
     public AbstractDAO getDAO() {
         return divisionDAO;
     }

    public Division getByName(String name , ProductContext context){
       return divisionDAO.getByName(name,context.getLoggedinCompany()) ;
    }
}