package com.primus.admin.region.service;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.AbstractService;
import com.primus.abstracts.TransactionUpdateDelta;
import com.primus.admin.region.model.Location;
import com.primus.admin.region.model.Region;
import com.primus.common.ProductContext;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import com.primus.abstracts.PrimusModel;
import com.primus.admin.region.dao.RegionDAO;

import java.util.List;


/**
** Class Generated by Primus Auto code generator
**/
@Component
@Transactional
public class RegionService extends AbstractService {


 @Autowired
 RegionDAO regionDAO ;

  @Override
     public AbstractDAO getDAO() {
         return regionDAO;
     }


      @Override
     protected void collateBeforUpdate(PrimusModel newObject, PrimusModel oldObject) {
         Region newObj = (Region) newObject;
         Region oldObj = (Region) oldObject;
         TransactionUpdateDelta delta = formDelta(oldObj.getLocations(),  newObj.getLocations()) ;
          newObj.getLocations().addAll((List<Location>)delta.getDeletedRecords());
     }

     public Location getLocationById(int locId, ProductContext context) {
        return (Location) regionDAO.getById(Location.class);

     }

    public Location getLocationByName(String locName, ProductContext context) {
        return (Location) regionDAO.fetchAllActive("Location" , " where name = '" + locName  +"'", "" );

    }

}