package com.primus.admin.region.model;

import com.primus.abstracts.PrimusBusinessModel;
import com.primus.common.FiniteValue;
import com.techtrade.rads.framework.annotations.RadsPropertySet;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;

@Entity
@Table(name = "LOCATIONS")
@AttributeOverrides({
        @AttributeOverride(name="ID", column=@Column(name="ID")),
        @AttributeOverride(name="createdDate", column=@Column(name="CREATED_DATE")),
        @AttributeOverride(name="createdBy", column=@Column(name="CREATED_BY")),
        @AttributeOverride(name="lastUpdateDate", column=@Column(name="LAST_UPDATED_DATE")),
        @AttributeOverride(name="lastUpdatedBy", column=@Column(name="LAST_UPDATED_BY")),
        @AttributeOverride(name="version", column=@Column(name="VERSION"))

})

/**
** Class Generated by Primus Auto code generator
**/
public class Location extends PrimusBusinessModel {

	String code ;

	
	@Column(name  ="LOCATION_CODE")
	public String  getCode ()
	{
		return code;
	}

	
	public void setCode ( String   val )
	{
		code  = val;
	}

	String name ;

	@RadsPropertySet(isBK =  true )
	@Column(name  ="LOCATION_NAME")
	public String  getName ()
	{
		return name;
	}

	@RadsPropertySet(isBK =  true )
	public void setName ( String   val )
	{
		name  = val;
	}

	FiniteValue locationType ;

	@RadsPropertySet(useBKForJSON =  true, useBKForMap = true, useBKForXML = true)
	@ManyToOne(cascade=CascadeType.DETACH)
	@JoinColumn(name  ="LOC_TYPE")
	public FiniteValue  getLocationType ()
	{
		return locationType;
	}

	@RadsPropertySet(useBKForJSON =  true, useBKForMap = true, useBKForXML = true)
	public void setLocationType ( FiniteValue   val )
	{
		locationType  = val;
	}

	Region region ;

	@RadsPropertySet(isBK =  true )
	@ManyToOne(cascade=CascadeType.DETACH)
	@JoinColumn(name  ="REGION_ID")
	public Region  getRegion ()
	{
		return region;
	}

	@RadsPropertySet(isBK =  true )
	public void setRegion ( Region   val )
	{
		region  = val;
	}

	String description ;

	
	@Column(name  ="DESCRIPTION")
	public String  getDescription ()
	{
		return description;
	}

	
	public void setDescription ( String   val )
	{
		description  = val;
	}




}