package com.primus.admin.zone.dao;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.PrimusModel;
import org.springframework.stereotype.Component;
import com.primus.admin.zone.model.Zone;

/**
** Class Generated by Primus Auto code generator
**/
@Component
public class ZoneDAO extends AbstractDAO{

  @Override
    public String getEntityClassName() {
        return  "Zone";
    }

    @Override
    public Class getEntityClass() {
        return  Zone.class;
    }

}

