package com.primus.merchandise.item.service;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.AbstractService;
import com.primus.merchandise.item.model.Item;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import com.primus.abstracts.PrimusModel;
import com.primus.merchandise.item.dao.ItemDAO;



/**
** Class Generated by Primus Auto code generator
**/
@Component
@Transactional
public class ItemService extends AbstractService {


 @Autowired
 ItemDAO itemDAO ;

  @Override
     public AbstractDAO getDAO() {
         return itemDAO;
     }


      @Override
     protected void collateBeforUpdate(PrimusModel newObject, PrimusModel oldObject) {
         Item newObj = (Item) newObject;
         Item oldObj = (Item) oldObject;
         /*TransactionUpdateDelta delta = formDelta(oldObj.getPayScaleSplits(), ((PayScale) newObj).getPayScaleSplits()) ;
         payScale.getPayScaleSplits().addAll((List<PayScaleSplit>)delta.getDeletedRecords());*/
     }

}