package com.primus.merchandise.item.service;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.AbstractService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import com.primus.abstracts.PrimusModel;



/**
** Class Generated by Primus Auto code generator
**/
@Component
@Transactional
public class SkuService extends AbstractService {


 //@Autowired
// SkuDAO skuDAO ;

  @Override
     public AbstractDAO getDAO() {
         return null;
     }


      @Override
     protected void collateBeforUpdate(PrimusModel newObject, PrimusModel oldObject) {
         com.primus.merchandise.item.model.Sku newObj = (com.primus.merchandise.item.model.Sku) newObject;
         com.primus.merchandise.item.model.Sku oldObj = (com.primus.merchandise.item.model.Sku) oldObject;
         /*TransactionUpdateDelta delta = formDelta(oldObj.getPayScaleSplits(), ((PayScale) newObj).getPayScaleSplits()) ;
         payScale.getPayScaleSplits().addAll((List<PayScaleSplit>)delta.getDeletedRecords());*/
     }

}