package com.primus.merchandise.item.service;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.AbstractService;
import com.primus.merchandise.item.model.Sku;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import com.primus.abstracts.PrimusModel;
import com.primus.merchandise.item.dao.SkuDAO;



/**
** Class Generated by Primus Auto code generator
**/
@Component
@Transactional
public class SkuService extends AbstractService {


 @Autowired
 SkuDAO skuDAO ;

  @Override
     public AbstractDAO getDAO() {
         return skuDAO;
     }


      @Override
     protected void collateBeforUpdate(PrimusModel newObject, PrimusModel oldObject) {
         Sku newObj = (Sku) newObject;
         Sku oldObj = (Sku) oldObject;
         /*TransactionUpdateDelta delta = formDelta(oldObj.getPayScaleSplits(), ((PayScale) newObj).getPayScaleSplits()) ;
         payScale.getPayScaleSplits().addAll((List<PayScaleSplit>)delta.getDeletedRecords());*/
     }

}