package com.primus.merchandise.item.service;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.AbstractService;
import com.primus.merchandise.item.model.UOM;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import com.primus.abstracts.PrimusModel;
import com.primus.merchandise.item.dao.UOMDAO;



/**
** Class Generated by Primus Auto code generator
**/
@Component
@Transactional
public class UOMService extends AbstractService {


 @Autowired
 UOMDAO uOMDAO ;

  @Override
     public AbstractDAO getDAO() {
         return uOMDAO;
     }


      @Override
     protected void collateBeforUpdate(PrimusModel newObject, PrimusModel oldObject) {
         UOM newObj = (UOM) newObject;
         UOM oldObj = (UOM) oldObject;
         /*TransactionUpdateDelta delta = formDelta(oldObj.getPayScaleSplits(), ((PayScale) newObj).getPayScaleSplits()) ;
         payScale.getPayScaleSplits().addAll((List<PayScaleSplit>)delta.getDeletedRecords());*/
     }

}