package com.primus.admin.role.dao;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.PrimusModel;
import org.springframework.stereotype.Component;
import com.primus.admin.role.model.Role;

/**
** Class Generated by Primus Auto code generator
**/
@Component
public class RoleDAO extends AbstractDAO{

  @Override
    public String getEntityClassName() {
        return  "Role";
    }

    @Override
    public Class getEntityClass() {
        return  Role.class;
    }

}

