package com.primus.admin.department.dao;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.PrimusModel;
import org.springframework.stereotype.Component;
import com.primus.admin.department.model.Department;

/**
** Class Generated by Primus Auto code generator
**/
@Component
public class DepartmentDAO extends AbstractDAO{

  @Override
    public String getEntityClassName() {
        return  "Department";
    }

    @Override
    public Class getEntityClass() {
        return  Department.class;
    }

}

