package com.primus.merchandise.product.service;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.AbstractService;
import com.primus.merchandise.product.model.Product;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import com.primus.abstracts.PrimusModel;
import com.primus.merchandise.product.dao.ProductDAO;



/**
** Class Generated by Primus Auto code generator
**/
@Component
@Transactional
public class ProductService extends AbstractService {


 @Autowired
 ProductDAO productDAO ;

  @Override
     public AbstractDAO getDAO() {
         return productDAO;
     }


      @Override
     protected void collateBeforUpdate(PrimusModel newObject, PrimusModel oldObject) {
         Product newObj = (Product) newObject;
         Product oldObj = (Product) oldObject;
         /*TransactionUpdateDelta delta = formDelta(oldObj.getPayScaleSplits(), ((PayScale) newObj).getPayScaleSplits()) ;
         payScale.getPayScaleSplits().addAll((List<PayScaleSplit>)delta.getDeletedRecords());*/
     }

}