package com.primus.admin.department.model;

import com.primus.abstracts.PrimusBusinessModel;
import com.primus.common.FiniteValue;
import com.techtrade.rads.framework.annotations.RadsPropertySet;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;

@Entity
@Table(name = "DEPARTMENTS")
@AttributeOverrides({
        @AttributeOverride(name="ID", column=@Column(name="ID")),
        @AttributeOverride(name="createdDate", column=@Column(name="CREATED_DATE")),
        @AttributeOverride(name="createdBy", column=@Column(name="CREATED_BY")),
        @AttributeOverride(name="lastUpdateDate", column=@Column(name="LAST_UPDATED_DATE")),
        @AttributeOverride(name="lastUpdatedBy", column=@Column(name="LAST_UPDATED_BY")),
        @AttributeOverride(name="version", column=@Column(name="VERSION"))

})

/**
** Class Generated by Primus Auto code generator
**/
public class Department extends PrimusBusinessModel {

	String code ;

		@Column(name  ="DEPARTMENT_CODE")
	public String  getCode ()
	{
		return code;
	}

		public void setCode ( String   val )
	{
		code  = val;
	}

	String name ;

		@RadsPropertySet(isBK =  true )
		@Column(name  ="DEPARTMENT_NAME")
	public String  getName ()
	{
		return name;
	}

		@RadsPropertySet(isBK =  true )
		public void setName ( String   val )
	{
		name  = val;
	}

	String description ;

		@Column(name  ="DESCRIPTION")
	public String  getDescription ()
	{
		return description;
	}

		public void setDescription ( String   val )
	{
		description  = val;
	}

	String manager ;

		@Column(name  ="MANAGER")
	public String  getManager ()
	{
		return manager;
	}

		public void setManager ( String   val )
	{
		manager  = val;
	}

	int noEmployees ;

		@Column(name  ="NO_EMPLOYEES")
	public int  getNoEmployees ()
	{
		return noEmployees;
	}

		public void setNoEmployees ( int   val )
	{
		noEmployees  = val;
	}




}