package com.primus.admin.reasoncode.controller;

import com.primus.abstracts.AbstractListController;
import com.primus.common.CommonUtil;
import com.primus.common.FVConstants;


import java.util.Map;

/**
** Class Generated by Primus Auto code generator
**/
public class ReasonCodeListController extends AbstractListController{

     @Override
       protected String getServiceName() {
           return "ReasonCodeService";
       }


    @Override
    protected String getAddEditPageKey() {
        return "newreasoncode";
    }

    @Override
    protected String getValidatorName() {
        return "ReasonCodeValidator";
    }

}