package com.primus.admin.reasoncode.controller;

import com.primus.abstracts.AbstractDataSheetController;;
import java.util.LinkedHashMap;
import java.util.Map;


/**
** Class Generated by Primus Auto code generator
**/
public class ReasonCodeController extends AbstractDataSheetController{

    @Override
    protected String getServiceName() {
        return "ReasonCodeService";
    }


    @Override
    protected String getValidatorName() {
        return "ReasonCodeValidator";
    }

     

}