package com.primus.merchandise.item.model;

import com.primus.abstracts.PrimusBusinessModel;
import com.primus.common.FiniteValue;
import com.primus.merchandise.product.model.Product;
import com.techtrade.rads.framework.annotations.RadsPropertySet;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;

@Entity
@Table(name = "ITEMS")
@AttributeOverrides({
        @AttributeOverride(name="ID", column=@Column(name="ID")),
        @AttributeOverride(name="createdDate", column=@Column(name="CREATED_DATE")),
        @AttributeOverride(name="createdBy", column=@Column(name="CREATED_BY")),
        @AttributeOverride(name="lastUpdateDate", column=@Column(name="LAST_UPDATED_DATE")),
        @AttributeOverride(name="lastUpdatedBy", column=@Column(name="LAST_UPDATED_BY")),
        @AttributeOverride(name="version", column=@Column(name="VERSION"))

})

/**
** Class Generated by Primus Auto code generator
**/
public class Item extends PrimusBusinessModel {

	String code ;

	
	@Column(name  ="CODE")
	public String  getCode ()
	{
		return code;
	}

	
	public void setCode ( String   val )
	{
		code  = val;
	}

	String name ;

	@RadsPropertySet(isBK =  true )
	@Column(name  ="ITEM_NAME")
	public String  getName ()
	{
		return name;
	}

	@RadsPropertySet(isBK =  true )
	public void setName ( String   val )
	{
		name  = val;
	}

	Product product ;

	@RadsPropertySet(useBKForJSON =  true, useBKForMap = true, useBKForXML = true)
	@ManyToOne(cascade=CascadeType.DETACH)
	@JoinColumn(name  ="PRODUCT_ID")
	public Product  getProduct ()
	{
		return product;
	}

	@RadsPropertySet(useBKForJSON =  true, useBKForMap = true, useBKForXML = true)
	public void setProduct ( Product   val )
	{
		product  = val;
	}

	FiniteValue medicineUOM ;

	@RadsPropertySet(useBKForJSON =  true, useBKForMap = true, useBKForXML = true)
	@ManyToOne(cascade=CascadeType.DETACH)
	@JoinColumn(name  ="MEDUNIT")
	public FiniteValue  getMedicineUOM ()
	{
		return medicineUOM;
	}

	@RadsPropertySet(useBKForJSON =  true, useBKForMap = true, useBKForXML = true)
	public void setMedicineUOM ( FiniteValue   val )
	{
		medicineUOM  = val;
	}

	Double taxRate ;

	
	@Column(name  ="TAX_RATE")
	public Double  getTaxRate ()
	{
		return taxRate;
	}

	
	public void setTaxRate ( Double   val )
	{
		taxRate  = val;
	}

	String description ;

	
	@Column(name  ="DESCRIPTION")
	public String  getDescription ()
	{
		return description;
	}

	
	public void setDescription ( String   val )
	{
		description  = val;
	}

	String ingrediants ;

	
	@Column(name  ="INGREDIENTS")
	public String  getIngrediants ()
	{
		return ingrediants;
	}

	
	public void setIngrediants ( String   val )
	{
		ingrediants  = val;
	}

	String usage ;

	
	@Column(name  ="MED_USAGE")
	public String  getUsage ()
	{
		return usage;
	}

	
	public void setUsage ( String   val )
	{
		usage  = val;
	}

	String storage ;

	
	@Column(name  ="STORAGE")
	public String  getStorage ()
	{
		return storage;
	}

	
	public void setStorage ( String   val )
	{
		storage  = val;
	}




}