package com.primus.merchandise.item.model;

import com.primus.abstracts.PrimusBusinessModel;
import com.primus.common.FiniteValue;
import com.techtrade.rads.framework.annotations.RadsPropertySet;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;

@Entity
@Table(name = "SKUS")
@AttributeOverrides({
        @AttributeOverride(name="ID", column=@Column(name="ID")),
        @AttributeOverride(name="createdDate", column=@Column(name="CREATED_DATE")),
        @AttributeOverride(name="createdBy", column=@Column(name="CREATED_BY")),
        @AttributeOverride(name="lastUpdateDate", column=@Column(name="LAST_UPDATED_DATE")),
        @AttributeOverride(name="lastUpdatedBy", column=@Column(name="LAST_UPDATED_BY")),
        @AttributeOverride(name="version", column=@Column(name="VERSION"))

})

/**
** Class Generated by Primus Auto code generator
**/
public class Sku extends PrimusBusinessModel {

	String code ;

	
	@Column(name  ="CODE")
	public String  getCode ()
	{
		return code;
	}

	
	public void setCode ( String   val )
	{
		code  = val;
	}

	String barcode ;

	
	@Column(name  ="BARCODE")
	public String  getBarcode ()
	{
		return barcode;
	}

	
	public void setBarcode ( String   val )
	{
		barcode  = val;
	}

	String name ;

	@RadsPropertySet(isBK =  true )
	@Column(name  ="SKU_NAME")
	public String  getName ()
	{
		return name;
	}

	@RadsPropertySet(isBK =  true )
	public void setName ( String   val )
	{
		name  = val;
	}

	Item item ;

	@RadsPropertySet(useBKForJSON =  true, useBKForMap = true, useBKForXML = true)
	@ManyToOne(cascade=CascadeType.DETACH)
	@JoinColumn(name  ="ITEM_ID")
	public Item  getItem ()
	{
		return item;
	}

	@RadsPropertySet(useBKForJSON =  true, useBKForMap = true, useBKForXML = true)
	public void setItem ( Item   val )
	{
		item  = val;
	}

	Double medUnitValue ;

	
	@Column(name  ="MED_UNIT_VALUE")
	public Double  getMedUnitValue ()
	{
		return medUnitValue;
	}

	
	public void setMedUnitValue ( Double   val )
	{
		medUnitValue  = val;
	}

	UOM uom ;

	@RadsPropertySet(useBKForJSON =  true, useBKForMap = true, useBKForXML = true)
	@ManyToOne(cascade=CascadeType.DETACH)
	@JoinColumn(name  ="UOM_ID")
	public UOM  getUom ()
	{
		return uom;
	}

	@RadsPropertySet(useBKForJSON =  true, useBKForMap = true, useBKForXML = true)
	public void setUom ( UOM   val )
	{
		uom  = val;
	}

	Double unitPerPack ;

	
	@Column(name  ="UNIT_PERPACK")
	public Double  getUnitPerPack ()
	{
		return unitPerPack;
	}

	
	public void setUnitPerPack ( Double   val )
	{
		unitPerPack  = val;
	}

	Double wholeSaleRate ;

	
	@Column(name  ="WHOLESALE_RATE")
	public Double  getWholeSaleRate ()
	{
		return wholeSaleRate;
	}

	
	public void setWholeSaleRate ( Double   val )
	{
		wholeSaleRate  = val;
	}

	Double retailRate ;

	
	@Column(name  ="RETAIL_RATE")
	public Double  getRetailRate ()
	{
		return retailRate;
	}

	
	public void setRetailRate ( Double   val )
	{
		retailRate  = val;
	}

	String description ;

	
	@Column(name  ="DESCRIPTION")
	public String  getDescription ()
	{
		return description;
	}

	
	public void setDescription ( String   val )
	{
		description  = val;
	}




}