package com.primus.merchandise.item.model;

import com.primus.abstracts.PrimusBusinessModel;
import com.primus.common.FiniteValue;
import com.techtrade.rads.framework.annotations.RadsPropertySet;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;

@Entity
@Table(name = "UOMS")
@AttributeOverrides({
        @AttributeOverride(name="ID", column=@Column(name="ID")),
        @AttributeOverride(name="createdDate", column=@Column(name="CREATED_DATE")),
        @AttributeOverride(name="createdBy", column=@Column(name="CREATED_BY")),
        @AttributeOverride(name="lastUpdateDate", column=@Column(name="LAST_UPDATED_DATE")),
        @AttributeOverride(name="lastUpdatedBy", column=@Column(name="LAST_UPDATED_BY")),
        @AttributeOverride(name="version", column=@Column(name="VERSION"))

})

/**
** Class Generated by Primus Auto code generator
**/
public class UOM extends PrimusBusinessModel {

	String code ;

	
	@Column(name  ="CODE")
	public String  getCode ()
	{
		return code;
	}

	
	public void setCode ( String   val )
	{
		code  = val;
	}

	String name ;

	@RadsPropertySet(isBK =  true )
	@Column(name  ="ITEM_NAME")
	public String  getName ()
	{
		return name;
	}

	@RadsPropertySet(isBK =  true )
	public void setName ( String   val )
	{
		name  = val;
	}

	String description ;

	
	@Column(name  ="DESCRIPTION")
	public String  getDescription ()
	{
		return description;
	}

	
	public void setDescription ( String   val )
	{
		description  = val;
	}

	Boolean saleSpecificUOM ;

	
	@Column(name  ="IS_SALE_SPECIFIC")
	public Boolean  getSaleSpecificUOM ()
	{
		return saleSpecificUOM;
	}

	
	public void setSaleSpecificUOM ( Boolean   val )
	{
		saleSpecificUOM  = val;
	}

	Boolean volumeSpecific ;

	
	@Column(name  ="IS_VOLUME_SPECIFIC")
	public Boolean  getVolumeSpecific ()
	{
		return volumeSpecific;
	}

	
	public void setVolumeSpecific ( Boolean   val )
	{
		volumeSpecific  = val;
	}




}