package com.primus.merchandise.item.model;

import com.primus.abstracts.PrimusBusinessModel;
import com.primus.abstracts.PrimusModel;
import com.primus.common.FiniteValue;
import com.techtrade.rads.framework.annotations.RadsPropertySet;
import com.techtrade.rads.framework.model.abstracts.ModelObject;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;
import java.util.Date;

@Entity
@Table(name = "UOMS")
/**
** Class Generated by Primus Auto code generator
**/
public class UOM extends PrimusModel {

	protected int id;

	String code ;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name  ="ID")
	@RadsPropertySet(isPK = true)
	public int getId() {
		return id;
	}

	@RadsPropertySet(isPK = true)
	public void setId(int id) {
		this.id = id;
	}


	@Column(name  ="CODE")
	public String  getCode ()
	{
		return code;
	}

	
	public void setCode ( String   val )
	{
		code  = val;
	}

	String name ;

	@RadsPropertySet(isBK =  true )
	@Column(name  ="NAME")
	public String  getName ()
	{
		return name;
	}

	@RadsPropertySet(isBK =  true )
	public void setName ( String   val )
	{
		name  = val;
	}

	String description ;

	
	@Column(name  ="DESCRIPTION")
	public String  getDescription ()
	{
		return description;
	}

	
	public void setDescription ( String   val )
	{
		description  = val;
	}

	Boolean saleSpecificUOM ;

	
	@Column(name  ="IS_SALE_SPECIFIC")
	public Boolean  getSaleSpecificUOM ()
	{
		return saleSpecificUOM;
	}

	
	public void setSaleSpecificUOM ( Boolean   val )
	{
		saleSpecificUOM  = val;
	}

	Boolean volumeSpecific ;


	@Column(name  ="IS_VOLUME_SPECIFIC")
	public Boolean  getVolumeSpecific ()
	{
		return volumeSpecific;
	}

	
	public void setVolumeSpecific ( Boolean   val )
	{
		volumeSpecific  = val;
	}




}