package com.primus.crm.appointment.dao;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.PrimusModel;
import org.springframework.stereotype.Component;
import com.primus.crm.appointment.model.Appointment;

/**
** Class Generated by Primus Auto code generator
**/
@Component
public class AppointmentDAO extends AbstractDAO{

  @Override
    public String getEntityClassName() {
        return  "Appointment";
    }

    @Override
    public Class getEntityClass() {
        return  Appointment.class;
    }

}

