package com.primus.crm.appointment.dao;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.PrimusModel;
import org.springframework.stereotype.Component;
import com.primus.crm.appointment.model.AppointmentTemplate;

/**
** Class Generated by Primus Auto code generator
**/
@Component
public class AppointmentTemplateDAO extends AbstractDAO{

  @Override
    public String getEntityClassName() {
        return  "AppointmentTemplate";
    }

    @Override
    public Class getEntityClass() {
        return  AppointmentTemplate.class;
    }

}

