package com.primus.admin.reasoncode.dao;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.PrimusModel;
import org.springframework.stereotype.Component;
import com.primus.admin.reasoncode.model.ReasonCode;

/**
** Class Generated by Primus Auto code generator
**/
@Component
public class ReasonCodeDAO extends AbstractDAO{

  @Override
    public String getEntityClassName() {
        return  "ReasonCode";
    }

    @Override
    public Class getEntityClass() {
        return  ReasonCode.class;
    }

}

