package com.primus.admin.division.model;

import com.primus.abstracts.PrimusBusinessModel;
import com.primus.admin.region.model.Location;
import com.primus.common.FiniteValue;
import com.primus.common.address.Address;
import com.techtrade.rads.framework.annotations.RadsPropertySet;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;


@Entity
@Table(name = "DIVISIONS")
@AttributeOverrides({
        @AttributeOverride(name = "ID", column = @Column(name = "ID")),
        @AttributeOverride(name = "createdDate", column = @Column(name = "CREATED_DATE")),
        @AttributeOverride(name = "createdBy", column = @Column(name = "CREATED_BY")),
        @AttributeOverride(name = "lastUpdateDate", column = @Column(name = "LAST_UPDATED_DATE")),
        @AttributeOverride(name = "lastUpdatedBy", column = @Column(name = "LAST_UPDATED_BY")),
        @AttributeOverride(name = "version", column = @Column(name = "VERSION"))

})
/**
 ** Class Generated by Primus Auto code generator
 **/
public class Division extends PrimusBusinessModel {

    String name;

    @RadsPropertySet(isBK = true)
    @Column(name = "DIVISION_NAME")
    public String getName() {
        return name;
    }

    @RadsPropertySet(isBK = true)
    public void setName(String val) {
        name = val;
    }

    String code;

    @Column(name = "DIVISION_CODE")
    public String getCode() {
        return code;
    }

    public void setCode(String val) {
        code = val;
    }


    String email;

    @Column(name = "EMAIL")
    public String getEmail() {
        return email;
    }

    public void setEmail(String val) {
        email = val;
    }


    String area;

    @Column(name = "AREA")
    public String getArea() {
        return area;
    }

    public void setArea(String val) {
        area = val;
    }

    FiniteValue divType;

    @ManyToOne(cascade=CascadeType.DETACH)
    @JoinColumn(name  ="INDUSTRY_TYPE")
    public FiniteValue getDivType() {
        return divType;
    }

    public void setDivType(FiniteValue val) {
        divType = val;
    }

    String manager;

    @Column(name = "MANAGER")
    public String getManager() {
        return manager;
    }

    public void setManager(String val) {
        manager = val;
    }

    String managerUserId;

    @Column(name = "MANAGER_USER_ID")
    public String getManagerUserId() {
        return managerUserId;
    }

    public void setManagerUserId(String managerUserId) {
        this.managerUserId = managerUserId;
    }

    int noEmployees;

    @Column(name = "NO_EMPLOYEES")
    public int getNoEmployees() {
        return noEmployees;
    }

    public void setNoEmployees(int val) {
        noEmployees = val;
    }

    Address address;

    @ManyToOne(cascade=CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name  ="ADDRESS_ID")
    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    Location location ;


    @RadsPropertySet(useBKForJSON = true, useBKForMap = true, useBKForXML = true)
    @ManyToOne(cascade = CascadeType.DETACH)
    @JoinColumn(name = "LOCATION_ID")
    public Location getLocation() {
        return location;
    }

    @RadsPropertySet(useBKForJSON = true, useBKForMap = true, useBKForXML = true)
    public void setLocation(Location location) {
        this.location = location;
    }
}