package com.primus.admin.division.model;

import com.primus.abstracts.PrimusBusinessModel;
import com.primus.common.FiniteValue;
import com.techtrade.rads.framework.annotations.RadsPropertySet;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;

@Entity
@Table(name = "DIVISIONS")
@AttributeOverrides({
        @AttributeOverride(name = "ID", column = @Column(name = "ID")),
        @AttributeOverride(name = "createdDate", column = @Column(name = "CREATED_DATE")),
        @AttributeOverride(name = "createdBy", column = @Column(name = "CREATED_BY")),
        @AttributeOverride(name = "lastUpdateDate", column = @Column(name = "LAST_UPDATED_DATE")),
        @AttributeOverride(name = "lastUpdatedBy", column = @Column(name = "LAST_UPDATED_BY")),
        @AttributeOverride(name = "version", column = @Column(name = "VERSION"))

})

/**
 ** Class Generated by Primus Auto code generator
 **/
public class Division extends PrimusBusinessModel {

    String name;

    @RadsPropertySet(isBK = true)
    @Column(name = "DIVISION_NAME")
    public String getName() {
        return name;
    }

    @RadsPropertySet(isBK = true)
    public void setName(String val) {
        name = val;
    }

    String code;

    @Column(name = "DIVISION_CODE")
    public String getCode() {
        return code;
    }

    public void setCode(String val) {
        code = val;
    }

    String address1;

    @Column(name = "ADDRESS1")
    public String getAddress1() {
        return address1;
    }

    public void setAddress1(String val) {
        address1 = val;
    }

    String address2;

    @Column(name = "ADDRESS2")
    public String getAddress2() {
        return address2;
    }

    public void setAddress2(String val) {
        address2 = val;
    }

    String zipcode;

    @Column(name = "ZIPCODE")
    public String getZipcode() {
        return zipcode;
    }

    public void setZipcode(String val) {
        zipcode = val;
    }

    String city;

    @Column(name = "CITY")
    public String getCity() {
        return city;
    }

    public void setCity(String val) {
        city = val;
    }

    String email;

    @Column(name = "EMAIL")
    public String getEmail() {
        return email;
    }

    public void setEmail(String val) {
        email = val;
    }

    String phone;

    @Column(name = "PHONE")
    public String getPhone() {
        return phone;
    }

    public void setPhone(String val) {
        phone = val;
    }

    String area;

    @Column(name = "AREA")
    public String getArea() {
        return area;
    }

    public void setArea(String val) {
        area = val;
    }

    FiniteValue divType;

    @Column(name = "DIV_TYPE")
    public FiniteValue getDivType() {
        return divType;
    }

    public void setDivType(FiniteValue val) {
        divType = val;
    }

    String manager;

    @Column(name = "MANAGER")
    public String getManager() {
        return manager;
    }

    public void setManager(String val) {
        manager = val;
    }

    int noEmployees;

    @Column(name = "NO_EMPLOYEES")
    public int getNoEmployees() {
        return noEmployees;
    }

    public void setNoEmployees(int val) {
        noEmployees = val;
    }


}