package com.primus.crm.appointment.service;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.AbstractService;
import com.primus.common.FVConstants;
import com.primus.common.FiniteValue;
import com.primus.common.ProductContext;
import com.primus.crm.appointment.model.Appointment;
import com.primus.crm.appointment.model.AppointmentTemplate;
import com.primus.framework.nextup.NextUpGenerator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;
import com.primus.abstracts.PrimusModel;
import com.primus.crm.appointment.dao.AppointmentDAO;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.TimeZone;


/**
** Class Generated by Primus Auto code generator
**/
@Component
@Transactional
public class AppointmentService extends AbstractService {


 @Autowired
 AppointmentDAO appointmentDAO ;

  @Override
     public AbstractDAO getDAO() {
         return appointmentDAO;
     }


      @Override
     protected void collateBeforUpdate(PrimusModel newObject, PrimusModel oldObject) {
         Appointment newObj = (Appointment) newObject;
         Appointment oldObj = (Appointment) oldObject;

         /*TransactionUpdateDelta delta = formDelta(oldObj.getPayScaleSplits(), ((PayScale) newObj).getPayScaleSplits()) ;
         payScale.getPayScaleSplits().addAll((List<PayScaleSplit>)delta.getDeletedRecords());*/

     }

    private Appointment formSkeltonFromTemplate(AppointmentTemplate template, ProductContext context) {
      Appointment appointment = new Appointment();
      appointment.setLocation(template.getLocation());
      appointment.setDoctor(template.getDoctor());
      appointment.setStockist(template.getStockist());
      appointment.setStore(template.getStore());
      appointment.setPartyType(template.getPartyType());
      appointment.setApptTime(template.getAppointmentTime());
      appointment.setAgent(template.getAgent());
      appointment.setTemplate(template);
      appointment.setCompany(template.getCompany());
      appointment.setStatus(new FiniteValue(FVConstants.APPT_STATUS.PLANNED));

      return appointment ;

    }



    private void generateMonthlyAppointments(AppointmentTemplate template, ProductContext context) {
        Date endDate = template.getEndAt();
        Date startDate = template.getStartFrom();
        
        Calendar startCalendar = Calendar.getInstance(TimeZone.getTimeZone("Asia/Calcutta"));
        startCalendar.setTime(startDate);
        Calendar endCalendar = Calendar.getInstance(TimeZone.getTimeZone("Asia/Calcutta"));
        endCalendar.setTime(endDate);


        int endYear = endCalendar.get(Calendar.YEAR);
        int startYear = startCalendar.get(Calendar.YEAR);

        int endMonth = endCalendar.get(Calendar.MONTH);
        int startMonth = startCalendar.get(Calendar.MONTH);

        int apptDate = template.getApptDayForMonth();

        int curYear = startYear;
        int curMonth = startMonth;
        while ((curMonth <= endMonth) || (curYear < endYear)) {
            Calendar apptCalendar = Calendar.getInstance();
            apptCalendar.setTimeZone(TimeZone.getTimeZone("Asia/Calcutta"));
            apptCalendar.set(Calendar.YEAR, curYear);
            apptCalendar.set(Calendar.MONTH, curMonth);
            apptCalendar.set(Calendar.DAY_OF_MONTH, apptDate);
            Appointment appointment = formSkeltonFromTemplate(template, context);
            appointment.setApptDate(apptCalendar.getTime());
            String no = NextUpGenerator.getNextNumber(FVConstants.PGM_APPT, context, null, template.getLocation().getRegion(), appointment.getApptDate());
            appointment.setDocNo(no);
            create(appointment, context);
            curMonth++;
            if (curMonth > 12) {
                curMonth = 1;
                curYear++;
            }

        }


    }

    private boolean  isStartLesser (int startYear, int startMon , int startWeek, int endYear,int endMonth, int endWeek)
    {
        Calendar startCalendar = Calendar.getInstance(TimeZone.getTimeZone("Asia/Calcutta"));
        startCalendar.set(Calendar.YEAR, startYear);
        startCalendar.set(Calendar.MONTH, startMon);
        startCalendar.set(Calendar.WEEK_OF_MONTH, startWeek);

        Calendar endCalendar = Calendar.getInstance(TimeZone.getTimeZone("Asia/Calcutta"));
        endCalendar.set(Calendar.YEAR, endYear);
        endCalendar.set(Calendar.MONTH, endMonth);
        endCalendar.set(Calendar.WEEK_OF_MONTH, endWeek);

        if(endCalendar.after(startCalendar)) return true;
        else return  false ;
    }

    private int getWeekofDay( int weekProduct ){

        if(weekProduct % 2 == 0) return 1;
        if(weekProduct % 3 == 0) return 2;
        if(weekProduct % 5 == 0) return 3;
        if(weekProduct % 7 == 0) return 4;
        if(weekProduct % 11 == 0) return 5;
        if(weekProduct % 13 == 0) return 6;
        if(weekProduct % 17 == 0) return 7;
        return  0;

    }

    private void generateWeeklyAppointments(AppointmentTemplate template, ProductContext context) {

        Date endDate = template.getEndAt();
        Date startDate = template.getStartFrom();

        Calendar startCalendar = Calendar.getInstance(TimeZone.getTimeZone("Asia/Calcutta"));
        startCalendar.setTime(startDate);
        Calendar endCalendar = Calendar.getInstance(TimeZone.getTimeZone("Asia/Calcutta"));
        endCalendar.setTime(endDate);


        int endYear = endCalendar.get(Calendar.YEAR);
        int startYear = startCalendar.get(Calendar.YEAR);

        int startWeek = startCalendar.get(Calendar.WEEK_OF_MONTH);
        int endWeek = endCalendar.get(Calendar.WEEK_OF_MONTH);

        int endMonth = endCalendar.get(Calendar.MONTH);
        int startMonth = startCalendar.get(Calendar.MONTH);

        int apptDate = getWeekofDay(template.getWeekDays());

        int curYear = startYear;
        int curMonth = startMonth;
        int curWeek = startWeek;

        while (isStartLesser(curYear,curMonth,curWeek,endYear,endMonth,endWeek))  {
            Calendar apptCalendar = Calendar.getInstance();
            apptCalendar.setTimeZone(TimeZone.getTimeZone("Asia/Calcutta"));
            apptCalendar.set(Calendar.YEAR, curYear);
            apptCalendar.set(Calendar.MONTH, curMonth);
            apptCalendar.set(Calendar.WEEK_OF_MONTH,curWeek);
            apptCalendar.set(Calendar.DAY_OF_WEEK, apptDate);

            Appointment appointment = formSkeltonFromTemplate(template, context);
            appointment.setApptDate(apptCalendar.getTime());
            String no = NextUpGenerator.getNextNumber(FVConstants.PGM_APPT, context, null, template.getLocation().getRegion(), appointment.getApptDate());
            appointment.setDocNo(no);
            create(appointment, context);
            curWeek ++ ;
            if (curMonth > 12) {
                curMonth = 1;
                curYear++;
                curWeek =1 ;
            } else if (curWeek > 4) {
                curWeek =1;
                curMonth ++;
            }


        }
    }

    private int getMonthEndDay(int year, int month)
    {
        if( (year % 4  == 0) && month == 2 )
            return 29;
        else if (month == 2)
            return 28;
        else if (month == 1 || month == 3  || month == 5 || month == 7 ||   month == 8  || month == 10 || month == 12  )
            return 31 ;
        else
            return 30;
    }

    private void generateDailyAppointments(AppointmentTemplate template, ProductContext context) {

        Date endDate = template.getEndAt();
        Date startDate = template.getStartFrom();

        Calendar startCalendar = Calendar.getInstance(TimeZone.getTimeZone("Asia/Calcutta"));
        startCalendar.setTime(startDate);
        Calendar endCalendar = Calendar.getInstance(TimeZone.getTimeZone("Asia/Calcutta"));
        endCalendar.setTime(endDate);


        int endYear = endCalendar.get(Calendar.YEAR);
        int startYear = startCalendar.get(Calendar.YEAR);


        int startDay = startCalendar.get(Calendar.DAY_OF_MONTH);
        int endDay = endCalendar.get(Calendar.DAY_OF_MONTH);

        int endMonth = endCalendar.get(Calendar.MONTH);
        int startMonth = startCalendar.get(Calendar.MONTH);

        int curYear = startYear;
        int curMonth = startMonth;
        int curDay = startDay;

        while (isStartLesser(curYear,curMonth,startDay,endYear,endMonth,endDay))  {
            Calendar apptCalendar = Calendar.getInstance();
            apptCalendar.setTimeZone(TimeZone.getTimeZone("Asia/Calcutta"));
            apptCalendar.set(Calendar.YEAR, curYear);
            apptCalendar.set(Calendar.MONTH, curMonth);
            apptCalendar.set(Calendar.DAY_OF_MONTH, curDay);
            int dayOfWeek =  apptCalendar.get(Calendar.DAY_OF_WEEK) ;
            int weekDays = template.getWeekDays() ;
            if ((weekDays % dayOfWeek) == 0) {
                Appointment appointment = formSkeltonFromTemplate(template, context);
                appointment.setApptDate(apptCalendar.getTime());
                String no = NextUpGenerator.getNextNumber(FVConstants.PGM_APPT, context, null, template.getLocation().getRegion(), appointment.getApptDate());
                appointment.setDocNo(no);
                create(appointment, context);
            }
            int monthEndDay = getMonthEndDay(curYear, curMonth) ;
            curDay  ++ ;
            if (curMonth > 12) {
                curMonth = 1;
                curYear++;
                curDay ++ ;
            } else if (curDay > monthEndDay) {
                curDay =1;
                curMonth ++;
            }


        }


    }

    private void generateBiWeeklyAppointments(AppointmentTemplate template, ProductContext context) {

        Date endDate = template.getEndAt();
        Date startDate = template.getStartFrom();

        Calendar startCalendar = Calendar.getInstance(TimeZone.getTimeZone("Asia/Calcutta"));
        startCalendar.setTime(startDate);
        Calendar endCalendar = Calendar.getInstance(TimeZone.getTimeZone("Asia/Calcutta"));
        endCalendar.setTime(endDate);


        int endYear = endCalendar.get(Calendar.YEAR);
        int startYear = startCalendar.get(Calendar.YEAR);

        int startWeek = startCalendar.get(Calendar.WEEK_OF_MONTH);
        int endWeek = endCalendar.get(Calendar.WEEK_OF_MONTH);

        int endMonth = endCalendar.get(Calendar.MONTH);
        int startMonth = startCalendar.get(Calendar.MONTH);

        int apptDate = getWeekofDay(template.getWeekDays());

        int curYear = startYear;
        int curMonth = startMonth;
        int curWeek = startWeek;

        while (isStartLesser(curYear,curMonth,curWeek,endYear,endMonth,endWeek))  {
            Calendar apptCalendar = Calendar.getInstance();
            apptCalendar.setTimeZone(TimeZone.getTimeZone("Asia/Calcutta"));
            apptCalendar.set(Calendar.YEAR, curYear);
            apptCalendar.set(Calendar.MONTH, curMonth);
            apptCalendar.set(Calendar.WEEK_OF_MONTH,curWeek);
            apptCalendar.set(Calendar.DAY_OF_WEEK, apptDate);

            Appointment appointment = formSkeltonFromTemplate(template, context);
            appointment.setApptDate(apptCalendar.getTime());
            String no = NextUpGenerator.getNextNumber(FVConstants.PGM_APPT, context, null, template.getLocation().getRegion(), appointment.getApptDate());
            appointment.setDocNo(no);
            create(appointment, context);
            curWeek +=2 ;
            if (curMonth > 12) {
                curMonth = 1;
                curYear++;
                curWeek =1 ;
            } else if (curWeek > 5) {
                curWeek =2;
                curMonth ++;
            }else if (curWeek > 4) {
                curWeek =1;
                curMonth ++;
            }


        }
    }

    @Transactional(propagation = Propagation.REQUIRED)
    public void createBulkAppointments(AppointmentTemplate template, ProductContext context)
     {
        if(template.getPattern().equals(FVConstants.DATE_PATTERN.MONTHLY)) {
            generateMonthlyAppointments(template,context);
        } else if(template.getPattern().equals(FVConstants.DATE_PATTERN.WEEKLY)) {
            generateWeeklyAppointments(template,context);
        }else if(template.getPattern().equals(FVConstants.DATE_PATTERN.BIWEEKLY)) {
            generateBiWeeklyAppointments(template,context);
        }else if(template.getPattern().equals(FVConstants.DATE_PATTERN.DAILY)) {
            generateDailyAppointments(template,context);
        }

     }

}