package com.primus.crm.appointment.service;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.AbstractService;
import com.primus.crm.appointment.model.AppointmentTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import com.primus.abstracts.PrimusModel;
import com.primus.crm.appointment.dao.AppointmentTemplateDAO;



/**
** Class Generated by Primus Auto code generator
**/
@Component
@Transactional
public class AppointmentTemplateService extends AbstractService {


 @Autowired
 AppointmentTemplateDAO appointmentTemplateDAO ;

  @Override
     public AbstractDAO getDAO() {
         return appointmentTemplateDAO;
     }


      @Override
     protected void collateBeforUpdate(PrimusModel newObject, PrimusModel oldObject) {
         AppointmentTemplate newObj = (AppointmentTemplate) newObject;
         AppointmentTemplate oldObj = (AppointmentTemplate) oldObject;
         /*TransactionUpdateDelta delta = formDelta(oldObj.getPayScaleSplits(), ((PayScale) newObj).getPayScaleSplits()) ;
         payScale.getPayScaleSplits().addAll((List<PayScaleSplit>)delta.getDeletedRecords());*/
     }

}