package com.primus.admin.zone.model;

import com.primus.abstracts.PrimusBusinessModel;
import com.primus.common.FiniteValue;
import com.techtrade.rads.framework.annotations.RadsPropertySet;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;

@Entity
@Table(name = "ZONES")
@AttributeOverrides({
        @AttributeOverride(name="ID", column=@Column(name="ID")),
        @AttributeOverride(name="createdDate", column=@Column(name="CREATED_DATE")),
        @AttributeOverride(name="createdBy", column=@Column(name="CREATED_BY")),
        @AttributeOverride(name="lastUpdateDate", column=@Column(name="LAST_UPDATED_DATE")),
        @AttributeOverride(name="lastUpdatedBy", column=@Column(name="LAST_UPDATED_BY")),
        @AttributeOverride(name="version", column=@Column(name="VERSION"))

})

/**
** Class Generated by Primus Auto code generator
**/
public class Zone extends PrimusBusinessModel {

	String name ;

	@RadsPropertySet(isBK =  true )
	@Column(name  ="NAME")
	public String  getName ()
	{
		return name;
	}

	@RadsPropertySet(isBK =  true )
	public void setName ( String   val )
	{
		name  = val;
	}

	FiniteValue zoneType ;

	@RadsPropertySet(useBKForJSON =  true, useBKForMap = true, useBKForXML = true)
	@ManyToOne(cascade=CascadeType.DETACH)
	@JoinColumn(name  ="ZONE_TYPE")
	public FiniteValue  getZoneType ()
	{
		return zoneType;
	}

	@RadsPropertySet(useBKForJSON =  true, useBKForMap = true, useBKForXML = true)
	public void setZoneType ( FiniteValue   val )
	{
		zoneType  = val;
	}

	String description ;

	
	@Column(name  ="DESCRIPTION")
	public String  getDescription ()
	{
		return description;
	}

	
	public void setDescription ( String   val )
	{
		description  = val;
	}




}