package com.primus.merchandise.product.dao;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.PrimusModel;
import org.springframework.stereotype.Component;
import com.primus.merchandise.product.model.Product;

/**
** Class Generated by Primus Auto code generator
**/
@Component
public class ProductDAO extends AbstractDAO{

  @Override
    public String getEntityClassName() {
        return  "Product";
    }

    @Override
    public Class getEntityClass() {
        return  Product.class;
    }

}

