package com.primus.admin.region.controller;

import com.primus.abstracts.AbstractCRUDController;;
import java.util.LinkedHashMap;
import java.util.Map;


/**
** Class Generated by Primus Auto code generator
**/
public class RegionController extends AbstractCRUDController{

    @Override
    protected String getServiceName() {
        return "RegionService";
    }


    @Override
    protected String getValidatorName() {
        return "RegionValidator";
    }

     

}