package com.primus.admin.region.controller;

import com.primus.abstracts.AbstractListController;
import com.primus.common.CommonUtil;
import com.primus.common.FVConstants;


import java.util.Map;

/**
** Class Generated by Primus Auto code generator
**/
public class RegionListController extends AbstractListController{

     @Override
       protected String getServiceName() {
           return "RegionService";
       }


    @Override
    protected String getAddEditPageKey() {
        return "newregion";
    }

    @Override
    protected String getValidatorName() {
        return "RegionValidator";
    }

}