package com.primus.merchandise.category.controller;

import com.primus.abstracts.AbstractDataSheetController;;
import java.util.LinkedHashMap;
import java.util.Map;


/**
** Class Generated by Primus Auto code generator
**/
public class CategoryController extends AbstractDataSheetController{

    @Override
    protected String getServiceName() {
        return "CategoryService";
    }


    @Override
    protected String getValidatorName() {
        return "CategoryValidator";
    }

     

}