package com.primus.merchandise.category.controller;

import com.primus.abstracts.AbstractListController;
import com.primus.common.CommonUtil;
import com.primus.common.FVConstants;


import java.util.Map;

/**
** Class Generated by Primus Auto code generator
**/
public class CategoryListController extends AbstractListController{

     @Override
       protected String getServiceName() {
           return "CategoryService";
       }


    @Override
    protected String getAddEditPageKey() {
        return "newcategory";
    }

    @Override
    protected String getValidatorName() {
        return "CategoryValidator";
    }

}