package com.primus.admin.department.service;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.AbstractService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import com.primus.admin.department.dao.DepartmentDAO;



/**
** Class Generated by Primus Auto code generator
**/
@Component
@Transactional
public class DepartmentService extends AbstractService {


 @Autowired
 DepartmentDAO departmentDAO ;

  @Override
     public AbstractDAO getDAO() {
         return departmentDAO;
     }

}