package com.primus.admin.department.validator;

import com.primus.abstracts.AbstractValidator;
import com.primus.abstracts.CommonErrorCodes;
import com.primus.abstracts.PrimusBusinessModel;
import com.primus.abstracts.PrimusModel;
import com.primus.common.ProductContext;
import com.techtrade.rads.framework.model.abstracts.RadsError;
import com.techtrade.rads.framework.utils.Utils;
import org.springframework.stereotype.Component;
import java.util.ArrayList;
import java.util.List;
import com.primus.admin.department.model.Department;


/**
** Class Generated by Primus Auto code generator
**/
@Component
public class DepartmentValidator extends AbstractValidator {

@Override
    public String getBusinessKeyField() {
        return "Department_Name";
    }

    @Override
    public List<RadsError> checkforMandatoryFields(PrimusModel model, ProductContext context) {
        Department department = (Department) model;
        List<RadsError> results =new ArrayList<RadsError>();
                if(Utils.isNullString(department.getCode  () ) ) {
            results.add( getErrorforCode(context, CommonErrorCodes.CANNOT_BE_EMPTY,"Department_Code"));
        }

                if(Utils.isNullString(department.getName  () ) ) {
            results.add( getErrorforCode(context, CommonErrorCodes.CANNOT_BE_EMPTY,"Department_Name"));
        }

        
        return results;

     }

     @Override
    public List<RadsError> checkforValueRanges(PrimusModel model, ProductContext context) {
        return null;
    }

    @Override
    public List<RadsError> adaptFromUI(PrimusModel model, ProductContext context) {
       super.adaptFromUI(model,context) ;
       return null;
    }
}