package com.primus.merchandise.category.dao;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.PrimusModel;
import org.springframework.stereotype.Component;
import com.primus.merchandise.category.model.Category;

/**
** Class Generated by Primus Auto code generator
**/
@Component
public class CategoryDAO extends AbstractDAO{

  @Override
    public String getEntityClassName() {
        return  "Category";
    }

    @Override
    public Class getEntityClass() {
        return  Category.class;
    }

}

