package com.primus.merchandise.item.dao;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.PrimusModel;
import org.springframework.stereotype.Component;
import com.primus.merchandise.item.model.Item;

/**
** Class Generated by Primus Auto code generator
**/
@Component
public class ItemDAO extends AbstractDAO{

  @Override
    public String getEntityClassName() {
        return  "Item";
    }

    @Override
    public Class getEntityClass() {
        return  Item.class;
    }

}

