package com.primus.merchandise.item.dao;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.PrimusModel;
import org.springframework.stereotype.Component;
import com.primus.merchandise.item.model.Sku;

/**
** Class Generated by Primus Auto code generator
**/
@Component
public class SkuDAO extends AbstractDAO{

  @Override
    public String getEntityClassName() {
        return  "Sku";
    }

    @Override
    public Class getEntityClass() {
        return  Sku.class;
    }

}

