package com.primus.merchandise.item.dao;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.PrimusModel;
import org.springframework.stereotype.Component;
import com.primus.merchandise.item.model.UOM;

/**
** Class Generated by Primus Auto code generator
**/
@Component
public class UOMDAO extends AbstractDAO{

  @Override
    public String getEntityClassName() {
        return  "UOM";
    }

    @Override
    public Class getEntityClass() {
        return  UOM.class;
    }

}

