package com.primus.admin.reasoncode.service;

import com.primus.abstracts.AbstractDAO;
import com.primus.abstracts.AbstractService;
import com.primus.admin.reasoncode.model.ReasonCode;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import com.primus.abstracts.PrimusModel;
import com.primus.admin.reasoncode.dao.ReasonCodeDAO;



/**
** Class Generated by Primus Auto code generator
**/
@Component
@Transactional
public class ReasonCodeService extends AbstractService {


 @Autowired
 ReasonCodeDAO reasonCodeDAO ;

  @Override
     public AbstractDAO getDAO() {
         return reasonCodeDAO;
     }


      @Override
     protected void collateBeforUpdate(PrimusModel newObject, PrimusModel oldObject) {
         ReasonCode newObj = (ReasonCode) newObject;
         ReasonCode oldObj = (ReasonCode) oldObject;

         /*TransactionUpdateDelta delta = formDelta(oldObj.getPayScaleSplits(), ((PayScale) newObj).getPayScaleSplits()) ;
         payScale.getPayScaleSplits().addAll((List<PayScaleSplit>)delta.getDeletedRecords());*/



     }

}