package com.primus.admin.role.controller;

import com.primus.abstracts.AbstractCRUDController;
import com.primus.abstracts.AbstractTransactionController;

/**
** Class Generated by Primus Auto code generator
**/
public class RoleController extends AbstractTransactionController{

    @Override
    protected String getServiceName() {
        return "RoleService";
    }


    @Override
    protected String getValidatorName() {
        return "RoleValidator";
    }


}