package com.primus.admin.role.controller;

import com.primus.abstracts.AbstractListController;
import com.primus.common.CommonUtil;
import com.primus.common.FVConstants;


import java.util.Map;

/**
** Class Generated by Primus Auto code generator
**/
public class RoleListController extends AbstractListController{

     @Override
    protected String getServiceName() {
           return "RoleService";
       }


    @Override
    protected String getAddEditPageKey() {
        return "newrole";
    }


    @Override
    protected String getValidatorName() {
        return "RoleValidator";
    }
}