package com.primus.admin.zone.controller;

import com.primus.abstracts.AbstractListController;
import com.primus.common.CommonUtil;
import com.primus.common.FVConstants;


import java.util.Map;

/**
** Class Generated by Primus Auto code generator
**/
public class ZoneListController extends AbstractListController{

     @Override
       protected String getServiceName() {
           return "ZoneService";
       }


    @Override
    protected String getAddEditPageKey() {
        return "newzone";
    }

    @Override
    protected String getValidatorName() {
        return "ZoneValidator";
    }

}