package com.primus.admin.zone.controller;

import com.primus.abstracts.AbstractDataSheetController;;
import java.util.LinkedHashMap;
import java.util.Map;


/**
** Class Generated by Primus Auto code generator
**/
public class ZoneController extends AbstractDataSheetController{

    @Override
    protected String getServiceName() {
        return "ZoneService";
    }


    @Override
    protected String getValidatorName() {
        return "ZoneValidator";
    }

     

}