package com.primus.admin.role.model;

import com.primus.abstracts.PrimusBusinessModel;
import com.primus.common.FiniteValue;
import com.techtrade.rads.framework.annotations.RadsPropertySet;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.Collection;

@Entity
@Table(name = "ROLES")
@AttributeOverrides({
        @AttributeOverride(name = "ID", column = @Column(name = "ID")),
        @AttributeOverride(name = "createdDate", column = @Column(name = "CREATED_DATE")),
        @AttributeOverride(name = "createdBy", column = @Column(name = "CREATED_BY")),
        @AttributeOverride(name = "lastUpdateDate", column = @Column(name = "LAST_UPDATED_DATE")),
        @AttributeOverride(name = "lastUpdatedBy", column = @Column(name = "LAST_UPDATED_BY")),
        @AttributeOverride(name = "version", column = @Column(name = "VERSION"))

})

/**
 ** Class Generated by Primus Auto code generator
 **/
public class Role extends PrimusBusinessModel {

    String role;

    @RadsPropertySet(isBK = true)
    @Column(name = "ROLE")
    public String getRole() {
        return role;
    }

    @RadsPropertySet(isBK = true)
    public void setRole(String val) {
        role = val;
    }

    String description;

    @Column(name = "DESCRIPTION")
    public String getDescription() {
        return description;
    }

    public void setDescription(String val) {
        description = val;
    }

    Collection<RoleModule> roleModules;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "role")
    public Collection<RoleModule> getRoleModules() {
        return roleModules;
    }

    public void setRoleModules(Collection<RoleModule> val) {
        roleModules = val;
    }

    public void addRoleModule(RoleModule roleModule)
    {
        if (roleModules == null)
            roleModules = new ArrayList<RoleModule>();
        roleModules.add(roleModule);
    }

    FiniteValue roleLevel;

    @ManyToOne(cascade=CascadeType.DETACH)
    @JoinColumn(name  ="ROLE_LEVEL")
    @RadsPropertySet(useBKForMap = true,useBKForJSON = true,useBKForXML = true)
    public FiniteValue getRoleLevel() {
        return roleLevel;
    }

    @RadsPropertySet(useBKForMap = true,useBKForJSON = true,useBKForXML = true)
    public void setRoleLevel(FiniteValue roleLevel) {
        this.roleLevel = roleLevel;
    }

    boolean adminAccess;
    boolean stockistAccess;
    boolean agentAccess;
    boolean financeAccess;
    boolean operationsAccess;
    boolean mgrPortalAccess;

    @Transient
    public boolean isAdminAccess() {
        return adminAccess;
    }

    public void setAdminAccess(boolean adminAccess) {
        this.adminAccess = adminAccess;
    }

    @Transient
    public boolean isStockistAccess() {
        return stockistAccess;
    }

    public void setStockistAccess(boolean stockistAccess) {
        this.stockistAccess = stockistAccess;
    }

    @Transient
    public boolean isAgentAccess() {
        return agentAccess;
    }

    public void setAgentAccess(boolean agentAccess) {
        this.agentAccess = agentAccess;
    }

    @Transient
    public boolean isFinanceAccess() {
        return financeAccess;
    }

    public void setFinanceAccess(boolean financeAccess) {
        this.financeAccess = financeAccess;
    }

    @Transient
    public boolean isOperationsAccess() {
        return operationsAccess;
    }

    public void setOperationsAccess(boolean operationsAccess) {
        this.operationsAccess = operationsAccess;
    }

    @Transient
    public boolean isMgrPortalAccess() {
        return mgrPortalAccess;
    }

    public void setMgrPortalAccess(boolean mgrPortalAccess) {
        this.mgrPortalAccess = mgrPortalAccess;
    }
}