package com.primus.admin.role.model;

import com.primus.abstracts.PrimusBusinessModel;
import com.primus.common.FiniteValue;
import com.techtrade.rads.framework.annotations.RadsPropertySet;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;

import com.primus.common.application.Module;

@Entity
@Table(name = "ROLE_MODULES")
@AttributeOverrides({
        @AttributeOverride(name = "ID", column = @Column(name = "ID")),
        @AttributeOverride(name = "createdDate", column = @Column(name = "CREATED_DATE")),
        @AttributeOverride(name = "createdBy", column = @Column(name = "CREATED_BY")),
        @AttributeOverride(name = "lastUpdateDate", column = @Column(name = "LAST_UPDATED_DATE")),
        @AttributeOverride(name = "lastUpdatedBy", column = @Column(name = "LAST_UPDATED_BY")),

        @AttributeOverride(name = "version", column = @Column(name = "VERSION"))

})

/**
 ** Class Generated by Primus Auto code generator
 **/
public class RoleModule extends PrimusBusinessModel {

    Role role;

    @RadsPropertySet(isBK = true ,excludeFromXML =  true, excludeFromMap =  true, excludeFromJSON = true)
    @ManyToOne(cascade = CascadeType.DETACH)
    @JoinColumn(name = "ROLE_ID")
    public Role getRole() {
        return role;
    }

    @RadsPropertySet(isBK = true ,excludeFromXML =  true, excludeFromMap =  true, excludeFromJSON = true)
    public void setRole(Role val) {
        role = val;
    }

    Module module;

    @RadsPropertySet(isBK = true)
    @ManyToOne(cascade = CascadeType.DETACH)
    @JoinColumn(name = "MODULE_CODE")
    public Module getModule() {
        return module;
    }

    @RadsPropertySet(isBK = true)
    public void setModule(Module val) {
        module = val;
    }

    boolean accessAllowed;

    @Column(name = "ACCESS_ALLOWED")
    public boolean getAccessAllowed() {
        return accessAllowed;
    }

    public void setAccessAllowed(boolean val) {
        accessAllowed = val;
    }


}